Emacs update scripts: add git status checks

diff --git a/emacs/usr/bin/em-commit-pkg-update b/emacs/usr/bin/em-commit-pkg-update
--- a/emacs/usr/bin/em-commit-pkg-update
+++ b/emacs/usr/bin/em-commit-pkg-update
@@ -2,7 +2,14 @@
 
 set -eu
 
-# TODO(laurynas): check git status
+# Must be no changes outside Emacs ELPA
+# TODO(laurynas): check that changes in elisp exist
+git_status=$(git status -s -u -- ':!emacs/.emacs.d/elpa')
+readonly git_status
+if [ -n "$git_status" ]; then
+    echo "Cannot commit Emacs package metadata update: changes outside emacs"
+    exit 1
+fi
 git add --all
 git commit -m "Emacs package update"
 git push
