Reformat shell scripts

diff --git a/emacs/usr/bin/em-commit-metadata-update b/emacs/usr/bin/em-commit-metadata-update
--- a/emacs/usr/bin/em-commit-metadata-update
+++ b/emacs/usr/bin/em-commit-metadata-update
@@ -8,8 +8,8 @@ pushd "$DOTFILES_ROOT" || exit
 non_elpa_status=$(git status -s -u -- ':!emacs/.emacs.d/elpa')
 readonly non_elpa_status
 if [ -n "$non_elpa_status" ]; then
-    echo "Cannot commit Emacs package metadata update: changes found outside emacs/.emacs.d/elpa/"
-    exit 1
+	echo "Cannot commit Emacs package metadata update: changes found outside emacs/.emacs.d/elpa/"
+	exit 1
 fi
 
 # Must be no changes in elisp files (source or compiled)
@@ -18,16 +18,16 @@ fi
 elisp_status=$(git status -s -u -- 'emacs/.emacs.d/elpa/**/*.el' 'emacs/.emacs.d/elpa/**/*.elc')
 readonly elisp_status
 if [ -n "$elisp_status" ]; then
-    echo "Cannot commit Emacs package metadata update: changes found in .el or .elc files in emacs/.emacs.d/elpa/"
-    exit 1
+	echo "Cannot commit Emacs package metadata update: changes found in .el or .elc files in emacs/.emacs.d/elpa/"
+	exit 1
 fi
 
 # Must have changes in elpa directory
 elpa_status=$(git status -s -u -- 'emacs/.emacs.d/elpa')
 readonly elpa_status
 if [ -z "$elpa_status" ]; then
-    echo "Cannot commit Emacs package metadata update: no changes found in emacs/.emacs.d/elpa/"
-    exit 1
+	echo "Cannot commit Emacs package metadata update: no changes found in emacs/.emacs.d/elpa/"
+	exit 1
 fi
 git add --all
 git commit -m "Emacs package metadata update"
diff --git a/emacs/usr/bin/em-commit-pkg-update b/emacs/usr/bin/em-commit-pkg-update
--- a/emacs/usr/bin/em-commit-pkg-update
+++ b/emacs/usr/bin/em-commit-pkg-update
@@ -8,16 +8,16 @@ pushd "$DOTFILES_ROOT" || exit
 non_elpa_status=$(git status -s -u -- ':!emacs/.emacs.d/elpa')
 readonly non_elpa_status
 if [ -n "$non_elpa_status" ]; then
-    echo "Cannot commit Emacs package update: changes found outside emacs/.emacs.d/elpa/"
-    exit 1
+	echo "Cannot commit Emacs package update: changes found outside emacs/.emacs.d/elpa/"
+	exit 1
 fi
 
 # Must have changes in elpa directory
 elpa_status=$(git status -s -u -- 'emacs/.emacs.d/elpa')
 readonly elpa_status
 if [ -z "$elpa_status" ]; then
-    echo "Cannot commit Emacs package update: no changes found in emacs/.emacs.d/elpa/"
-    exit 1
+	echo "Cannot commit Emacs package update: no changes found in emacs/.emacs.d/elpa/"
+	exit 1
 fi
 git add --all
 git commit -m "Emacs package update"
diff --git a/git/usr/bin/gitrmworktree b/git/usr/bin/gitrmworktree
--- a/git/usr/bin/gitrmworktree
+++ b/git/usr/bin/gitrmworktree
@@ -4,24 +4,24 @@ set -euo pipefail
 
 declare -i FORCE=0
 
-while (( $# > 0 )); do
-    case "$1" in
-        --force)
-            FORCE=1
-            shift
-            ;;
-        *)
-            if [[ -z "${WORKTREE_PATH:-}" ]]; then
-                readonly WORKTREE_PATH="$1"
-            fi
-            shift
-            ;;
-    esac
+while (($# > 0)); do
+	case "$1" in
+	--force)
+		FORCE=1
+		shift
+		;;
+	*)
+		if [[ -z "${WORKTREE_PATH:-}" ]]; then
+			readonly WORKTREE_PATH="$1"
+		fi
+		shift
+		;;
+	esac
 done
 
 if [ -z "${WORKTREE_PATH:-}" ]; then
-    echo "Usage: $0 [--force] <worktree-path>"
-    exit 3
+	echo "Usage: $0 [--force] <worktree-path>"
+	exit 3
 fi
 
 readonly WORKTREE_DIR="$WORKTREE_PATH:t"
@@ -36,16 +36,15 @@ readonly BRANCH_NAME
 
 REMOTE_NAME=$(git config branch."${BRANCH_NAME}".pushremote || echo "")
 if [ -z "${REMOTE_NAME}" ]; then
-    REMOTE_NAME=$(git config branch."${BRANCH_NAME}".remote || echo "")
+	REMOTE_NAME=$(git config branch."${BRANCH_NAME}".remote || echo "")
 fi
 readonly REMOTE_NAME
 
 if [ -z "${REMOTE_NAME}" ]; then
-    2>&1 echo "Failed to find push remote name for branch $BRANCH_NAME"
-    popd || exit 1
-    exit 3
+	2>&1 echo "Failed to find push remote name for branch $BRANCH_NAME"
+	popd || exit 1
+	exit 3
 fi
-
 
 cd "$(git rev-parse --git-dir)"
 cd ../../../
@@ -53,16 +52,16 @@ cd ../../../
 git pull
 
 if [ $FORCE -ne 1 ]; then
-    # TODO(laurynas): replace hardcoded "master" with the default branch check,
-    # i.e. git remote show [remote-name] | grep 'HEAD branch'
-    git branch --contains "$BRANCH_NAME" | grep -q master
-    readonly BRANCH_MERGED=$?
+	# TODO(laurynas): replace hardcoded "master" with the default branch check,
+	# i.e. git remote show [remote-name] | grep 'HEAD branch'
+	git branch --contains "$BRANCH_NAME" | grep -q master
+	readonly BRANCH_MERGED=$?
 
-    if [ $BRANCH_MERGED -ne 0 ]; then
-        echo "Branch $BRANCH_NAME checked out at $WORKTREE_DIR is not fully merged"
-        popd || exit 1
-        exit 2
-    fi
+	if [ $BRANCH_MERGED -ne 0 ]; then
+		echo "Branch $BRANCH_NAME checked out at $WORKTREE_DIR is not fully merged"
+		popd || exit 1
+		exit 2
+	fi
 fi
 
 rm -rf "$WORKTREE_ABSOLUTE_PATH"
@@ -71,13 +70,13 @@ popd -n
 git worktree prune
 
 if ! git push "$REMOTE_NAME" -d "$BRANCH_NAME"; then
-    echo "Failed to delete the remote branch, perhaps it was already deleted"
+	echo "Failed to delete the remote branch, perhaps it was already deleted"
 fi
 
 if [ $FORCE -ne 1 ]; then
-    git branch -d "$BRANCH_NAME"
+	git branch -d "$BRANCH_NAME"
 else
-    git branch -D "$BRANCH_NAME"
+	git branch -D "$BRANCH_NAME"
 fi
 
 git fetch --all -p
diff --git a/mysql-work/usr/bin/reupmerge b/mysql-work/usr/bin/reupmerge
--- a/mysql-work/usr/bin/reupmerge
+++ b/mysql-work/usr/bin/reupmerge
@@ -9,16 +9,16 @@ readonly HIGHER=$3
 pushd "$WORK_SRC_ROOT" || exit 1
 
 if ! pushd "$BRANCH-$HIGHER"; then
-    echo "Failed to pushd to $BRANCH-$HIGHER, check args"
-    exit 1
+	echo "Failed to pushd to $BRANCH-$HIGHER, check args"
+	exit 1
 fi
 
 readonly base_rev="$(git rev-list HEAD -1 --skip=1 --first-parent --topo-order)"
 readonly tmp_patch=$(mktemp)
 readonly tmp_patch_commit=$(mktemp)
 echo "Saving $BRANCH-$HIGHER last commit on top of $base_rev"
-git log --format=%B -1 > "$tmp_patch_commit"
-git log -1 -p -m --first-parent --pretty=email --full-index --binary > "$tmp_patch"
+git log --format=%B -1 >"$tmp_patch_commit"
+git log -1 -p -m --first-parent --pretty=email --full-index --binary >"$tmp_patch"
 
 popd || exit 1
 
